### ISSUE TITLE
拔刀版本？？？

### ISSUE THREAD

**Issue by xxlio109** [0999312/SlashBlade-Japanese-Addon-Pack#4]
SJAP_V1.0.8_MC1.12.2
SlashBlade-mc1.12-r16
TLS_V1.2.4_MC1.12.2
`[12:40:18] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: mods.flammpfeil.slashblade.entity.EntityWitherSword.func_70016_h(DDD)V
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:297) [SpongeImplHooks.class:1.12.2-2768-7.1.5]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zjm000(MinecraftServer.java:3963) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NoSuchMethodError: mods.flammpfeil.slashblade.entity.EntityWitherSword.func_70016_h(DDD)V
	at net.lrsoft.mrblade.specialattack.SA_CraftRev.doSpacialAttack(SA_CraftRev.java:95) ~[SA_CraftRev.class:?]
	at mods.flammpfeil.slashblade.item.ItemSlashBlade.doChargeAttack(ItemSlashBlade.java:1481) ~[ItemSlashBlade.class:?]
	at mods.flammpfeil.slashblade.item.ItemSlashBlade.func_77615_a(ItemSlashBlade.java:1562) ~[ItemSlashBlade.class:?]
	at net.minecraft.item.ItemStack.func_77974_b(ItemStack.java:548) ~[aip.class:?]
	at net.minecraft.entity.EntityLivingBase.redirect$onStopPlayerUsing$zeh000(EntityLivingBase.java:4281) ~[vp.class:?]
	at net.minecraft.entity.EntityLivingBase.func_184597_cx(EntityLivingBase.java:2816) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_184597_cx(EntityPlayerMP.java:4647) ~[oq.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:666) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[lp.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[lp.class:?]
	at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) ~[PacketPhaseUtil.class:1.12.2-2768-7.1.5]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zli000(SourceFile:539) ~[hv$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 7 more
[12:40:20] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: mods.flammpfeil.slashblade.entity.EntityWitherSword.func_70016_h(DDD)V
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:297) [SpongeImplHooks.class:1.12.2-2768-7.1.5]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zjm000(MinecraftServer.java:3963) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NoSuchMethodError: mods.flammpfeil.slashblade.entity.EntityWitherSword.func_70016_h(DDD)V
	at net.lrsoft.mrblade.specialattack.SA_CraftRev.doSpacialAttack(SA_CraftRev.java:95) ~[SA_CraftRev.class:?]
	at mods.flammpfeil.slashblade.item.ItemSlashBlade.doChargeAttack(ItemSlashBlade.java:1481) ~[ItemSlashBlade.class:?]
	at mods.flammpfeil.slashblade.item.ItemSlashBlade.func_77615_a(ItemSlashBlade.java:1562) ~[ItemSlashBlade.class:?]
	at net.minecraft.item.ItemStack.func_77974_b(ItemStack.java:548) ~[aip.class:?]
	at net.minecraft.entity.EntityLivingBase.redirect$onStopPlayerUsing$zeh000(EntityLivingBase.java:4281) ~[vp.class:?]
	at net.minecraft.entity.EntityLivingBase.func_184597_cx(EntityLivingBase.java:2816) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_184597_cx(EntityPlayerMP.java:4647) ~[oq.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:666) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[lp.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[lp.class:?]
	at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) ~[PacketPhaseUtil.class:1.12.2-2768-7.1.5]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zli000(SourceFile:539) ~[hv$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 7 more
[12:40:21] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: mods.flammpfeil.slashblade.entity.EntityWitherSword.func_70016_h(DDD)V
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:297) [SpongeImplHooks.class:1.12.2-2768-7.1.5]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zjm000(MinecraftServer.java:3963) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NoSuchMethodError: mods.flammpfeil.slashblade.entity.EntityWitherSword.func_70016_h(DDD)V
	at net.lrsoft.mrblade.specialattack.SA_CraftRev.doSpacialAttack(SA_CraftRev.java:95) ~[SA_CraftRev.class:?]
	at mods.flammpfeil.slashblade.item.ItemSlashBlade.doChargeAttack(ItemSlashBlade.java:1481) ~[ItemSlashBlade.class:?]
	at mods.flammpfeil.slashblade.item.ItemSlashBlade.func_77615_a(ItemSlashBlade.java:1562) ~[ItemSlashBlade.class:?]
	at net.minecraft.item.ItemStack.func_77974_b(ItemStack.java:548) ~[aip.class:?]
	at net.minecraft.entity.EntityLivingBase.redirect$onStopPlayerUsing$zeh000(EntityLivingBase.java:4281) ~[vp.class:?]
	at net.minecraft.entity.EntityLivingBase.func_184597_cx(EntityLivingBase.java:2816) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_184597_cx(EntityPlayerMP.java:4647) ~[oq.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:666) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[lp.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[lp.class:?]
	at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) ~[PacketPhaseUtil.class:1.12.2-2768-7.1.5]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zli000(SourceFile:539) ~[hv$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 7 more
[12:40:23] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: mods.flammpfeil.slashblade.entity.EntityWitherSword.func_70016_h(DDD)V
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:297) [SpongeImplHooks.class:1.12.2-2768-7.1.5]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zjm000(MinecraftServer.java:3963) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NoSuchMethodError: mods.flammpfeil.slashblade.entity.EntityWitherSword.func_70016_h(DDD)V
	at net.lrsoft.mrblade.specialattack.SA_CraftRev.doSpacialAttack(SA_CraftRev.java:95) ~[SA_CraftRev.class:?]
	at mods.flammpfeil.slashblade.item.ItemSlashBlade.doChargeAttack(ItemSlashBlade.java:1481) ~[ItemSlashBlade.class:?]
	at mods.flammpfeil.slashblade.item.ItemSlashBlade.func_77615_a(ItemSlashBlade.java:1562) ~[ItemSlashBlade.class:?]
	at net.minecraft.item.ItemStack.func_77974_b(ItemStack.java:548) ~[aip.class:?]
	at net.minecraft.entity.EntityLivingBase.redirect$onStopPlayerUsing$zeh000(EntityLivingBase.java:4281) ~[vp.class:?]
	at net.minecraft.entity.EntityLivingBase.func_184597_cx(EntityLivingBase.java:2816) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_184597_cx(EntityPlayerMP.java:4647) ~[oq.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:666) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[lp.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[lp.class:?]
	at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) ~[PacketPhaseUtil.class:1.12.2-2768-7.1.5]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zli000(SourceFile:539) ~[hv$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 7 more`

**Comment by 0999312** [comment]
错误不是SJAP和TLS导致的，而是别的附属导致的
